# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: DS CheatSheets
site_url: https://github.com/fralfaro/DS-Cheat-Sheets
site_author: Francisco Alfaro
site_description:

# Repository
repo_name: fralfaro/DS-Cheat-Sheets
repo_url: https://github.com/fralfaro/DS-Cheat-Sheets
edit_uri: ''


# Markdown extensions
markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed
  - neoteroi.cards
  - neoteroi.timeline
  - neoteroi.projects

extra_css:
  - css/neoteroi-mkdocs.css

# Extra javascript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Theme
theme:
  name: material
  language: en
  logo: images/rpython.svg
  favicon: images/icon.png
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  - navigation.indexes
  - content.tooltips
  - navigation.path
  - content.code.annotate
  - content.code.copy
  - content.code.select
  - navigation.tabs
  - navigation.footer
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: black
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fralfaro
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/fralfaro
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/faam/
    - icon: fontawesome/brands/kaggle
      link: https://www.kaggle.com/faamds
    - icon: fontawesome/brands/medium
      link: https://medium.com/@fralfaro
    - icon: fontawesome/solid/globe
      link: https://fralfaro.github.io/portfolio/

# Plugins
plugins:
  - mkdocs-jupyter:
      kernel_name: python3
  - search

# TOC
nav:
    - 🏠 Home: index.md
    - 📗 Python:
        - Python: examples/python/python.ipynb
        - Numpy: examples/numpy/numpy.ipynb
        - Pandas: examples/pandas/pandas.ipynb
        - Matplotlib: examples/matplotlib/matplotlib.ipynb
        - Scikit-Learn: examples/scikit-learn/sklearn.ipynb
        - Polars: examples/polars/polars.ipynb
    - 📘 R:
        - Dplyr: examples/dplyr/dplyr.ipynb
        - Ggplot2: examples/ggplot2/ggplot2.ipynb
        - Forcats: examples/forcats/forcats.ipyn





